name: stock_barcode_scanner
description: Barcode scanner for goods in stock
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mobile_scanner: ^3.5.2
  sqlite3: ^2.1.0
  sqlite3_flutter_libs: ^0.5.17
  path_provider: ^2.1.1
  path: ^1.8.3
  intl: ^0.18.1
  flutter_mailer:
    git:
      url: https://github.com/AdamVe/flutter_mailer
      ref: adamve/main

  flutter_riverpod: ^2.4.5
  riverpod_annotation: ^2.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.3

flutter:
  uses-material-design: true

